name: Level 1 - Yoshi's Island

on:
  workflow_dispatch: {} # TODO: Bonus opdracht, vervang door een echte trigger.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Configureer Java 21 en Gradle
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

#  gradle:
#    runs-on: ubuntu-latest

#    steps:
      - name: Setup Gradle je weet
        uses: gradle/actions/setup-gradle@v5

    # TODO - Run een gradle build command
